"""Generate manuscript assets from released aggregate results."""
from pathlib import Path
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]
FINAL=ROOT/'reference_results'
DIAG=FINAL/'diagnostics'
FIGURES=ROOT/'figures'
TABLES=ROOT/'tables'
GENERATED=ROOT/'scalars'
for directory in (FIGURES,TABLES,GENERATED): directory.mkdir(parents=True,exist_ok=True)
def nn_metrics(): return pd.read_csv(FINAL/'neural_head_metrics.csv')
ENCODERS = {
    "resnet50": "ResNet50",
    "vgg16": "VGG16",
    "inception_v3": "InceptionV3",
    "mobilenet_v2": "MobileNetV2",
    "coco_deeplab": "COCO semantic",
    "ade20k_segformer": "ADE20K semantic",
    "dinov2_vitb14": "DINOv2-B/14",
    "siglip2_b16": "SigLIP 2-B/16",
    "convnext_b": "ConvNeXt-B",
    "vit_b16": "ViT-B/16",
}
RESULTS=FINAL
def fmt(value,digits=4):return f'{float(value):.{digits}f}'
def macro(lines: list[str], name: str, value: object) -> None:
    lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

def main() -> None:
    for directory in (TABLES, FIGURES, GENERATED):
        directory.mkdir(parents=True, exist_ok=True)
    fixed = pd.read_csv(RESULTS / "fixed_metrics.csv")
    repeated = pd.read_csv(RESULTS / "repeated_metrics.csv")

    comparison = json.loads((RESULTS/"stack_vs_selected_paired_bootstrap.json").read_text())

    selected = fixed.loc[fixed.method.eq("siglip2_b16")].iloc[0]
    stack = fixed.loc[fixed.method.eq("linear_stack")].iloc[0]
    selected_repeated = repeated.loc[repeated.method.eq("siglip2_b16"), "test_accuracy"]
    stack_repeated = repeated.loc[repeated.method.eq("linear_stack"), "test_accuracy"]
    selected_count = int(repeated.loc[repeated.validation_selected_single & repeated.method.eq("siglip2_b16"), "split_index"].nunique())
    stack_preferred_count = int(repeated.loc[repeated.validation_preferred_method & repeated.method.eq("linear_stack"), "split_index"].nunique())

    lines = ["% Generated by analysis/generate_flowers_artifacts.py. Do not edit."]
    macro(lines, "FlowersSelectedValLoss", fmt(selected.validation_loss))
    macro(lines, "FlowersSelectedAcc", fmt(selected.test_accuracy))
    macro(lines, "FlowersSelectedBalanced", fmt(selected.test_balanced_accuracy))
    macro(lines, "FlowersSelectedMacro", fmt(selected.test_macro_f1))
    macro(lines, "FlowersSelectedLogLoss", fmt(selected.test_log_loss))
    macro(lines, "FlowersStackValLoss", fmt(stack.validation_loss))
    macro(lines, "FlowersStackAcc", fmt(stack.test_accuracy))
    macro(lines, "FlowersStackLogLoss", fmt(stack.test_log_loss))
    macro(lines, "FlowersStackAccuracyDifference", fmt(comparison["accuracy_difference"]))
    macro(lines, "FlowersStackLogLossDifference", fmt(comparison["log_loss_difference"]))
    macro(lines, "FlowersRepeatedSelectedCount", selected_count)
    macro(lines, "FlowersRepeatedStackPreferredCount", stack_preferred_count)
    macro(lines, "FlowersRepeatedSelectedMean", fmt(selected_repeated.mean()))
    macro(lines, "FlowersRepeatedSelectedSD", fmt(selected_repeated.std(ddof=1)))
    macro(lines, "FlowersRepeatedStackMean", fmt(stack_repeated.mean()))
    macro(lines, "FlowersRepeatedStackSD", fmt(stack_repeated.std(ddof=1)))
    (GENERATED / "flowers_scalars.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    rows = []
    for key, label in ENCODERS.items():
        row = fixed.loc[fixed.method.eq(key)].iloc[0]
        rows.append(f"{label} & {fmt(row.test_accuracy)} & {fmt(row.test_balanced_accuracy)} & {fmt(row.test_macro_f1)} & {fmt(row.test_log_loss)}\\\\")
    (TABLES / "encoder_performance.tex").write_text(
        "\n".join([
            r"\begin{table}[!htbp]", r"\centering\small", r"\caption{Locked-test Flowers performance after training-only tuning. Selection uses outer-validation log loss.}",
            r"\label{tab:flowers-performance}", r"\begin{tabular}{lrrrr}", r"\toprule", r"Representation & Accuracy & Balanced acc. & Macro F1 & Log loss\\", r"\midrule",
            *rows, r"\bottomrule", r"\end{tabular}", r"\end{table}",
        ]) + "\n", encoding="utf-8"
    )

    acc_lo, acc_hi = comparison["accuracy_interval"]
    loss_lo, loss_hi = comparison["log_loss_interval"]
    uncertainty_rows = [
        f"Accuracy & {fmt(comparison['selected_accuracy'])} & {fmt(comparison['stack_accuracy'])} & {fmt(comparison['accuracy_difference'])} $[{fmt(acc_lo)},{fmt(acc_hi)}]$\\\\",
        f"Log loss & {fmt(comparison['selected_log_loss'])} & {fmt(comparison['stack_log_loss'])} & {fmt(comparison['log_loss_difference'])} $[{fmt(loss_lo)},{fmt(loss_hi)}]$\\\\",
    ]
    (TABLES / "paired_uncertainty.tex").write_text(
        "\n".join([
            r"\begin{table}[!htbp]", r"\centering\small", r"\caption{Paired Flowers comparison from fixed fitted test predictions. Differences are stack minus selected single.}",
            r"\label{tab:flowers-uncertainty}", r"\begin{tabular}{lrrr}", r"\toprule", r"Metric & SigLIP~2 & Out-of-fold stack & Difference (95\% CI)\\", r"\midrule",
            *uncertainty_rows, r"\bottomrule", r"\end{tabular}", r"\end{table}",
        ]) + "\n", encoding="utf-8"
    )

    stability_rows = [
        f"SigLIP~2 & {fmt(selected_repeated.mean())} & {fmt(selected_repeated.std(ddof=1))} & $[{fmt(selected_repeated.quantile(.025))},{fmt(selected_repeated.quantile(.975))}]$ & {selected_count}/12 selected\\\\",
        f"All-ten cross-fitted stack & {fmt(stack_repeated.mean())} & {fmt(stack_repeated.std(ddof=1))} & $[{fmt(stack_repeated.quantile(.025))},{fmt(stack_repeated.quantile(.975))}]$ & {stack_preferred_count}/12 preferred\\\\",
    ]
    (TABLES / "split_stability.tex").write_text(
        "\n".join([
            r"\begin{table}[!htbp]", r"\centering\small", r"\caption{Flowers split stability under nested out-of-fold fitting and outer-validation selection.}",
            r"\label{tab:flowers-stability}", r"\begin{tabular}{lrrrl}", r"\toprule", r"Procedure & Mean acc. & SD & Empirical 95\% range & Selection frequency\\", r"\midrule",
            *stability_rows, r"\bottomrule", r"\end{tabular}", r"\end{table}",
        ]) + "\n", encoding="utf-8"
    )

    plt.style.use("seaborn-v0_8-whitegrid")
    encoder_fixed = fixed.loc[fixed.method_type.eq("encoder")].copy()
    fig, axis = plt.subplots(figsize=(8.5, 4.2))
    colors = ["#2563eb" if method == "siglip2_b16" else "#9ca3af" for method in encoder_fixed.method]
    axis.barh(range(len(encoder_fixed)), encoder_fixed.validation_loss, color=colors)
    axis.set_yticks(range(len(encoder_fixed)), [ENCODERS[key] for key in encoder_fixed.method])
    axis.invert_yaxis()
    axis.set_xlabel("Outer-validation log loss (lower is better)")
    fig.tight_layout()
    fig.savefig(FIGURES / "validation_selection.pdf", bbox_inches="tight")
    plt.close(fig)

    fig, axis = plt.subplots(figsize=(7.4, 3.8))
    for position, (label, values, color) in enumerate((("SigLIP 2", selected_repeated, "#2563eb"), ("Out-of-fold stack", stack_repeated, "#f59e0b"))):
        mean = values.mean(); lower = values.quantile(.025); upper = values.quantile(.975)
        axis.errorbar(mean, position, xerr=[[mean - lower], [upper - mean]], fmt="o", color=color, capsize=4, ms=7)
    axis.set_yticks([0, 1], ["SigLIP 2", "Out-of-fold stack"])
    axis.set_xlabel("Test accuracy across twelve splits")
    axis.invert_yaxis()
    fig.tight_layout()
    fig.savefig(FIGURES / "split_stability.pdf", bbox_inches="tight")
    plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.4))
    for axis, point, interval, title in zip(
        axes,
        (comparison["accuracy_difference"], comparison["log_loss_difference"]),
        (comparison["accuracy_interval"], comparison["log_loss_interval"]),
        ("Accuracy", "Log loss"),
    ):
        axis.errorbar(point, 0, xerr=[[point - interval[0]], [interval[1] - point]], fmt="o", color="#d62728", capsize=4)
        axis.axvline(0, color="#6b7280", ls="--", lw=1)
        axis.set_yticks([]); axis.set_title(title); axis.set_xlabel("Stack minus selected single")
    fig.tight_layout()
    fig.savefig(FIGURES / "paired_uncertainty.pdf", bbox_inches="tight")
    plt.close(fig)

    cost=json.loads((RESULTS/'extraction_costs.json').read_text())
    times=[float(cost[key].get('extraction_seconds',cost[key].get('cached_creation_extraction_seconds'))) for key in ENCODERS]
    fig, axis = plt.subplots(figsize=(7.2, 4.3))
    axis.scatter(times, encoder_fixed.validation_loss, color="#2563eb")
    for xx, yy, key in zip(times, encoder_fixed.validation_loss, encoder_fixed.method):
        axis.annotate(ENCODERS[key].replace(" semantic", ""), (xx, yy), xytext=(3, 3), textcoords="offset points", fontsize=7)
    axis.set_xlabel("Recorded extraction seconds (3,668 images)")
    axis.set_ylabel("Outer-validation log loss")
    fig.tight_layout()
    fig.savefig(FIGURES / "cost_performance.pdf", bbox_inches="tight")
    plt.close(fig)
if __name__=='__main__':main()
