"""Generate manuscript assets from released aggregate results."""
from pathlib import Path
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]
FINAL=ROOT/'aggregate_results'
DIAG=FINAL/'diagnostics'
FIGURES=ROOT/'figures'
TABLES=ROOT/'tables'
GENERATED=ROOT/'scalars'
for directory in (FIGURES,TABLES,GENERATED): directory.mkdir(parents=True,exist_ok=True)
def nn_metrics(): return pd.read_csv(FINAL/'neural_head_metrics.csv')
DATASETS = ["toronto_houses", "obs_horses", "breakhis", "pneumonia", "facial_age", "rice_disease"]
NAMES = {
    "toronto_houses": "Houses", "obs_horses": "Horses", "breakhis": "BreaKHis",
    "pneumonia": "Pneumonia", "facial_age": "Facial age", "rice_disease": "Rice disease",
}
ENCODERS = {
    "resnet50": "ResNet50", "vgg16": "VGG16", "inception_v3": "InceptionV3",
    "mobilenet_v2": "MobileNetV2", "coco_deeplab": "COCO semantic",
    "ade20k_segformer": "ADE20K semantic", "dinov2_vitb14": "DINOv2-B/14",
    "siglip2_b16": "SigLIP 2-B/16", "convnext_b": "ConvNeXt-B", "vit_b16": "ViT-B/16",
}
METHODS = {
    "equal_average": "equal average", "linear_stack": "linear stack",
    "greedy_average": "selected subset", "feature_concatenation": "feature union",
}
PREFIX = {
    "toronto_houses": "House", "obs_horses": "Horse", "breakhis": "BreakHis",
    "pneumonia": "Pneumonia", "facial_age": "Age", "rice_disease": "Rice",
}
def num(value,digits=3): return f'{float(value):.{digits}f}'
def metric_column(dataset: str) -> str:
    if dataset in {"toronto_houses", "obs_horses"}:
        return "test_r2"
    if dataset == "facial_age":
        return "test_mae"
    return "test_accuracy"

def macro(lines: list[str], name: str, value: object) -> None:
    lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

def generate_scalars(headline: pd.DataFrame, repeated: pd.DataFrame, nn: pd.DataFrame) -> None:
    bootstrap = json.loads((FINAL / "fixed_paired_bootstrap.json").read_text(encoding="utf-8"))
    lines = ["% Generated by analysis/generate_manuscript_tables.py. Do not edit."]
    for dataset in DATASETS:
        row = headline.loc[headline.dataset.eq(dataset)].iloc[0]
        prefix = PREFIX[dataset]
        macro(lines, prefix + "ResNet", num(row.resnet_test))
        macro(lines, prefix + "Selected", num(row.selected_encoder_test))
        macro(lines, prefix + "SelectedName", ENCODERS[row.selected_encoder])
        macro(lines, prefix + "Preferred", num(row.preferred_method_test))
        macro(lines, prefix + "PreferredName", METHODS.get(row.validation_preferred_method, ENCODERS.get(row.validation_preferred_method, row.validation_preferred_method)))
        macro(lines, prefix + "Gain", num(row.preferred_gain_over_selected_single))
        macro(lines, prefix + "GainLower", num(row.gain_interval_lower_95))
        macro(lines, prefix + "GainUpper", num(row.gain_interval_upper_95))
        rep = repeated.loc[repeated.dataset.eq(dataset)].iloc[0]
        macro(lines, prefix + "RepeatedSelected", num(rep.selected_mean))
        macro(lines, prefix + "RepeatedPreferred", num(rep.preferred_mean))
        macro(lines, prefix + "RepeatedGain", num(rep.mean_gain))
        macro(lines, prefix + "RepeatedSD", num(rep.preferred_sd))
    age = pd.read_csv(FINAL / "continuous_age_fixed_metrics.csv").set_index("method")
    for method, suffix in (("siglip2_b16", "Selected"), ("linear_stack", "Preferred")):
        macro(lines, "Age" + suffix + "RMSE", num(age.loc[method, "rmse"]))
        macro(lines, "Age" + suffix + "Correlation", num(age.loc[method, "correlation"]))
        macro(lines, "Age" + suffix + "WithinFive", num(100 * age.loc[method, "within_five_years"], 1) + r"\%")
    horse = json.loads((DIAG / "horse_grouping_audit.json").read_text(encoding="utf-8"))
    macro(lines, "HorseGroupCount", f"{horse['final_group_count']:,}")
    macro(lines, "HorseMultiGroups", f"{horse['multi_row_groups']:,}")
    macro(lines, "HorseMaxGroup", horse["max_group_size"])
    logme = pd.read_csv(DIAG / "logme_rank_diagnostics.csv")
    macro(lines, "LogMEMedianValidationRho", num(logme.spearman_logme_vs_validation_rank.median()))
    macro(lines, "LogMEWinnerAgreement", f"{int(logme.validation_winner_agreement.sum())}/6")
    duplicate = pd.read_csv(DIAG / "age_near_duplicate_sensitivity.csv").iloc[0]
    macro(lines, "AgeDuplicateFlagged", int(duplicate.flagged))
    macro(lines, "AgeDuplicateTotal", int(duplicate.test_n))
    macro(lines, "AgeDuplicateMAE", num(duplicate.mae_after_exclusion))
    rice = pd.read_csv(DIAG / "rice_easy_manifold_sensitivity.csv").iloc[0]
    macro(lines, "RiceCloseShare", num(100 * rice.flagged_share, 1) + r"\%")
    macro(lines, "RiceOneNN", num(rice.one_nn_accuracy))
    matched = pd.read_csv(DIAG / "matched_capacity_summary.csv").set_index("dataset")
    macro(lines, "MatchedHouseGap", num(matched.loc["toronto_houses", "mean"]))
    macro(lines, "MatchedHorseGap", num(matched.loc["obs_horses", "mean"]))
    macro(lines, "MatchedAgeGap", num(matched.loc["facial_age", "mean"]))
    light = pd.read_csv(DIAG / "light_adaptation" / "averaged_prediction_metrics.csv").set_index("model")
    macro(lines, "LightDino", num(light.loc["dinov2_vitb14", "seed_averaged_r2"]))
    macro(lines, "LightResNet", num(light.loc["resnet50", "seed_averaged_r2"]))
    macro(lines, "LightGap", num(light.loc["dinov2_vitb14", "seed_averaged_r2"] - light.loc["resnet50", "seed_averaged_r2"]))
    fixed = pd.read_csv(FINAL / "fixed_all_methods.csv")
    correlations = []
    for dataset in DATASETS:
        column = metric_column(dataset)
        left = fixed.loc[(fixed.dataset.eq(dataset)) & (fixed.method_type.eq("encoder")), ["method", column]]
        right = nn.loc[nn.dataset.eq(dataset), ["encoder", column]].rename(columns={"encoder": "method"})
        correlations.append(left.merge(right, on="method", suffixes=("_linear", "_nn")).iloc[:, 1:].corr(method="spearman").iloc[0, 1])
    macro(lines, "MedianNNRankCorrelation", num(np.nanmedian(correlations)))
    lines.append("% Exact package commit: 877908c916573109b2106cd5fec82ec83a6153de")
    macro(lines, "PackageCommit", r"\nolinkurl{877908c916573109b2106cd5fec82ec83a6153de}")
    (GENERATED / "scalars.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

def generate_tables(headline: pd.DataFrame, repeated: pd.DataFrame, fixed: pd.DataFrame, nn: pd.DataFrame) -> None:
    rows = []
    for dataset in DATASETS:
        row = headline.loc[headline.dataset.eq(dataset)].iloc[0]
        metric = "MAE" if dataset == "facial_age" else ("$R^2$" if dataset in {"toronto_houses", "obs_horses"} else "acc.")
        selected = f"{num(row.selected_encoder_test)} ({ENCODERS[row.selected_encoder]})"
        preferred_name = METHODS.get(row.validation_preferred_method, ENCODERS.get(row.validation_preferred_method, row.validation_preferred_method))
        preferred = f"{num(row.preferred_method_test)} ({preferred_name})"
        interval = f"{num(row.preferred_gain_over_selected_single)} $[{num(row.gain_interval_lower_95)},{num(row.gain_interval_upper_95)}]$"
        rows.append(f"{NAMES[dataset]} ({metric}) & {num(row.resnet_test)} & {selected} & {preferred} & {interval}\\\\")
    (TABLES / "generated_headline.tex").write_text("\n".join([
        r"\begin{tabular}{lcccc}", r"\toprule", r"Dataset & ResNet & Selected single & Preferred procedure & Gain (95\% CI)\\", r"\midrule",
        *rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")

    rows = []
    for dataset in DATASETS:
        row = repeated.loc[repeated.dataset.eq(dataset)].iloc[0]
        freq = json.loads(row.selected_encoder_frequencies)
        maximum = max(freq.values())
        leaders = ", ".join(ENCODERS[key] for key, value in freq.items() if value == maximum)
        rows.append(f"{NAMES[dataset]} & {leaders} ({maximum}/12) & {num(row.selected_mean, 6 if dataset == "rice_disease" else 3)} & {num(row.preferred_mean, 6 if dataset == "rice_disease" else 3)} & {num(row.mean_gain, 6 if dataset == "rice_disease" else 3)} & {num(row.preferred_sd)}\\\\")
    (TABLES / "generated_repeated.tex").write_text("\n".join([
        r"\begin{tabular}{lccccc}", r"\toprule", r"Dataset & Most selected & Single mean & Preferred mean & Mean gain & Preferred SD\\", r"\midrule",
        *rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")

    enc = fixed.loc[fixed.method_type.eq("encoder")]
    reg_rows, class_rows = [], []
    for key, label in ENCODERS.items():
        house = enc.loc[(enc.dataset.eq("toronto_houses")) & (enc.method.eq(key)), "test_r2"].iloc[0]
        horse = enc.loc[(enc.dataset.eq("obs_horses")) & (enc.method.eq(key)), "test_r2"].iloc[0]
        age = enc.loc[(enc.dataset.eq("facial_age")) & (enc.method.eq(key)), "test_mae"].iloc[0]
        reg_rows.append(f"{label} & {num(house,4)} & {num(horse,4)} & {num(age,3)}\\\\")
        vals = [enc.loc[(enc.dataset.eq(dataset)) & (enc.method.eq(key)), "test_accuracy"].iloc[0] for dataset in ("breakhis", "pneumonia", "rice_disease")]
        class_rows.append(f"{label} & " + " & ".join(num(value,4) for value in vals) + r"\\")
    (TABLES / "generated_single_regression.tex").write_text("\n".join([r"\begin{tabular}{lrrr}", r"\toprule", r"Encoder & Houses $R^2$ & Horses $R^2$ & Age MAE\\", r"\midrule", *reg_rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")
    (TABLES / "generated_single_classification.tex").write_text("\n".join([r"\begin{tabular}{lrrr}", r"\toprule", r"Encoder & BreaKHis & Pneumonia & Rice\\", r"\midrule", *class_rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")

    methods = ["equal_average", "linear_stack", "greedy_average", "feature_concatenation"]
    combo_rows = []
    for method in methods:
        values = []
        for dataset in DATASETS:
            row = fixed.loc[(fixed.dataset.eq(dataset)) & (fixed.method.eq(method))].iloc[0]
            values.append(num(row[metric_column(dataset)], 4))
        combo_rows.append(f"{METHODS[method].title()} & " + " & ".join(values) + r"\\")
    (TABLES / "generated_combinations.tex").write_text("\n".join([r"\begin{tabular}{lrrrrrr}", r"\toprule", r"Method & House & Horse & BreaKHis & Pneum. & Age MAE & Rice\\", r"\midrule", *combo_rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")

    motivation = []
    for key, label in ENCODERS.items():
        values = []
        for dataset in ("toronto_houses", "obs_horses"):
            linear = enc.loc[(enc.dataset.eq(dataset)) & (enc.method.eq(key)), "test_r2"].iloc[0]
            neural = nn.loc[(nn.dataset.eq(dataset)) & (nn.encoder.eq(key)), "test_r2"].iloc[0]
            values.extend([num(linear, 4), num(neural, 4)])
        motivation.append(f"{label} & " + " & ".join(values) + r"\\")
    (TABLES / "generated_nn_motivation.tex").write_text("\n".join([r"\begin{tabular}{lrrrr}", r"\toprule", r"& \multicolumn{2}{c}{Houses} & \multicolumn{2}{c}{Horses}\\", r"Encoder & Linear & NN & Linear & NN\\", r"\midrule", *motivation, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")

    logme = pd.read_csv(DIAG / "logme_rank_diagnostics.csv")
    logme_rows = [f"{NAMES[row.dataset]} & {num(row.spearman_logme_vs_validation_rank)} & {ENCODERS[row.logme_top]} & {'yes' if row.validation_winner_agreement else 'no'}\\\\" for row in logme.itertuples()]
    (TABLES / "generated_logme.tex").write_text("\n".join([r"\begin{tabular}{lrrr}", r"\toprule", r"Dataset & Spearman $\rho$ & LogME top & Agrees with validation\\", r"\midrule", *logme_rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")

    age_nn = nn.loc[nn.dataset.eq("facial_age"), ["encoder", "test_mae", "seed_mae_sd"]]
    age_rows = [f"{ENCODERS[row.encoder]} & {num(row.test_mae)} & {num(row.seed_mae_sd)}\\\\" for row in age_nn.itertuples()]
    (TABLES / "generated_age_nn.tex").write_text("\n".join([r"\begin{tabular}{lrr}", r"\toprule", r"Encoder & Test MAE & Seed SD\\", r"\midrule", *age_rows, r"\bottomrule", r"\end{tabular}"]) + "\n", encoding="utf-8")
if __name__=='__main__':
    headline=pd.read_csv(FINAL/'fixed_headline.csv')
    repeated=pd.read_csv(FINAL/'repeated_summary.csv')
    fixed=pd.read_csv(FINAL/'fixed_all_methods.csv')
    nn=nn_metrics()
    generate_scalars(headline,repeated,nn)
    generate_tables(headline,repeated,fixed,nn)
